#### Python II
****Today we talk about Booleans. We also look at some of the important libraries such as Matplotlib, NumPy, and Pandas. Finally, we will talk about how to write our own functions in Python.****

### Exercise
- Booleans represent one of the two values: `True` or `False` in Python.
- They are very helpful when comparing strings and mathematical expressions in Python.

In [ ]:
# Do Not run this cell! 
# When we see an expression that combines mathematical operators with Boolean operators
# and comparators, we will follow this order: 

1. Math operators (according to their order of operations).
2. Boolean comparators (==, !=, >, >=, <, <=). 
3. not operator (negation).
4. and operator. 
5. or operator. 

# It is always a good idea to include parentheses when working with complex expressions to make sure 
# that the intent is clear.

In [1]:
True + True + (False * 5)

In [2]:
True ** False

In [3]:
True != False

In [4]:
x = -4 
(x ** 2) + (4 * x) == False

In [3]:
a = 5
b = 10
c = 15 

h = a - b < -c 
i = a < a 
j = c <= c or c < a 
k = a != c and a > b - c

In [5]:
print(h)
print(i)
print(j)
print(k)

In [6]:
l = not k 
print(l)

In [46]:

a = 5
b = 10
c = 15
x = (b > a) and (c < b) or (not (a + b > c))
y = (b + a >= c) or (c / a > b / a)

In [7]:
print(x)

In [8]:
print(y)

In [9]:
"apples" > "oranges"

In [10]:
"apples" > "apple"

# **1. Matplotlib**

In [48]:
import matplotlib.pyplot as plt

In [ ]:
# Do not run this cell! 
# Useful package to visualize the data. 

import matplotlib.pyplot as plt                     # For importing the package as "plt".
%matplotlib inline



# Pie Charts 
plt.pie(list_of_counts, labels = list_of_labels);   # list_of_counts is a list containing the counts
                                                    # and list_of_labels is the corresponding list with  
                                                    # labels associated with different counts. 


# Bar Graphs 
plt.bar(list_of_labels, list_of_counts);            # Notice the order for list_of_counts and 
                                                    # list_of_labels switches from above. 


# Histograms 
plt.hist(quant_variable, edgecolor = 'k', bins = n, alpha = 0.5, density = True, label = "my_label");
                                                    # quant_variable is the list containing the values 
                                                    # values of the Quantitative variable and "n" is
                                                    # the bin size.


# For plotting two quantitative variables. 
plt.plot(quant_1, quant_2, '.', label = "my_label")  
plt.scatter(quant_1, quant_2, color = "color_column") # for plotting quant_2 as a function of quant_1.                                               



# Some useful functions. (a and b are arbitrary/placeholder strings)
plt.xlabel("a");
plt.xticks(rotation = n);
plt.ylabel("b");
plt.legend();
plt.figure(figsize = (n, k));
plt.title("my_title");

# For subplots. 
plt.subplot(i,j,k);




# For image show (along with colorbar) where N is an ndarray (with appropriate dimension and entries).  
plt.imshow(N);
plt.colorbar();


# For Box Plot where N is an ndarray.  
plt.boxplot([N], labels = ["my_label"], showfliers = False);

### Main Question: Is ***Netflix*** increasingly focusing on TV rather than movies in recent years?
- To answer the above question, let us analyse a data set collected by Fixable which is third party Netflix search engine. 
- This dataset consists of tv shows and movies available on Netflix as of 2019.

In [49]:
import pandas as pd
netflix = pd.read_csv("netflix.csv")
netflix.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",9-Sep-19,2019,TV-PG,90 min,"Children & Family Movies, Comedies"
1,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,9-Sep-16,2016,TV-MA,94 min,Stand-Up Comedy
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,8-Sep-18,2013,TV-Y7-FV,1 Season,Kids' TV
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,8-Sep-18,2016,TV-Y7,1 Season,Kids' TV
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,8-Sep-17,2017,TV-14,99 min,Comedies

In [50]:
# Which column (variable) is most helpful in answering our main question?
# Let us extract this column and convert it into a Python list called netflix_type. 

netflix_type = netflix["type"].to_list()
print(type(netflix_type),len(netflix_type), netflix_type[0:10])

<class 'list'> 6234 ['Movie', 'Movie', 'TV Show', 'TV Show', 'Movie', 'TV Show', 'Movie', 'Movie', 'TV Show', 'Movie']

In [51]:
# How many items in the list netflix_type are movies? Store your answer as movie_count. 
movie_count = netflix_type.count("Movie")
movie_count

4265

In [52]:
# How many items in the list netflix_type are TV shows? Store your answer as tv_show_count. 
tv_show_count = netflix_type.count("TV Show")
tv_show_count

1969

####  Proportions

In [27]:
# What is the proportion of TV shows in the list netflix_type?

####  Pie Chart

In [32]:
# Let us first create a list containing the counts for movies and tv shows. 

type_count = 

# Let us also create a list with labels for the above counts. 

type_labels =

In [31]:
# Let us now create Pie chart.

####  Bar Graphs

In [33]:
# Let us also create a Bar Graph.

# **2. NumPy**

In [53]:
import numpy as np

In [ ]:
# In what follows X_1, X_2, .... are arbitrary/placeholder lists, and 
# N is arbitrary/placeholder ndarray. 



# For importing the NumPy package as np. 
import numpy as np




# Creating NumPy arrays (ndarrays).

np.array(X_1)                          # For creating one dimensional ndarray from the list X_1. 

np.arange(j,k)                         # Will create an ndarray with integers j through (k-1).

np.array([X_1, X_2 ,...., X_m])        # For creating a matrix with m rows and n = len(X_1) columns where 
                                       # row 1 contains entries from X_1, row 2 contains entries from X_2
                                       # and so on. (We require lengths of X_1, ...., X_m be equal.)

np.zeros(X_1)                          # For creating a tensor with all entries equal to zero where 
                                       # the list X_1 contain information about the dimensions. 








# For extraction/slicing. 
N[j:k]                                 # For extracting elements j through (k-1).
N[j:k, m:n, ...., r:s]                 # For extracting elements from different axes (provided N 
                                       # is a higher dimensional ndarray).





# Some important functions and methods for ndarrays. 

np.sum(N)                              # Computes sum of the entries. 
np.sum(N, index = k)                   # Computes sum along axis k.
np.mean(N)                             # Computes average of the entries.
np.mean(N, index = k)                  # Computes average along axis k.
np.median(N)                           # Computes median of the entries. 
np.max(N)                              # Computes maximum of the entries. 
np.min(N)                              # Computes minimum of the entries. 
np.std(N)                              # Computes standard deviation of the entries. 
np.percentile(N, [25, 50, 75])         # Computes 25th, 50th, and 75th percentiles. 
np.cumsum(N)                           # Returns ndarray with cumulative sums. 
np.diff(N)                             # Returns ndarray with differences of adjacent elements. 

N.dtype                                # Returns the type of the ndarray N. 
N.shape                                # Returns the size (dimension) of the ndarray N. 
N.astype("")                           # For converting between dtypes. 


np.random.rand(n)                      # Generates n random numbers bewtween 0 and 1. 
np.repeat                              # For repeating each element of the array after themselves. 
np.concatenate                         # To join a sequence of arrays along an existing axis. 
np.random.permutation                  # Randomly permutes a sequence. 
np.unique                              # Returns a sorted unique elements of an array.

### **NumPy - Basics**

In [54]:
my_array_1 = np.array([1.5, 2.0])
print(my_array_1)

my_array_2 = np.array([1.5, 2])
print(my_array_2)

my_array_3 = np.array([1.5, "2"])
print(my_array_3)

[1.5 2. ]
[1.5 2. ]
['1.5' '2']

In [2]:
# Create an ndarray containing first five prime numbers starting with 2. Store it as first_five_primes.

In [3]:
# Create an ndarry containing first five alphabets. Store it as first_five_alpha.

In [4]:
# Create an ndarry containing boolean entries True and False. Store it as boolean_array.

In [5]:
# Print the dtypes of above three ndarrays.

In [6]:
# Replace the number 2 in first_five_primes with the boolean True. 




# Print the modified ndarray and its dtype.

In [7]:
# Replace the alphabet b in first_five_alphabets with the element 2. 



# Print the modified ndarray and its type.

In [8]:
# In the above modified ndarray, check if 2 is a number or a string?



# You can also use following: 
#type(first_five_alpha[1])

In [9]:
# Print an ndarray of first 100 positive integers.

### **NumPy - Boolean Masking**

In [56]:
# Let us reload the Netflix data 
import pandas as pd
netflix = pd.read_csv("netflix.csv")
netflix.head(3)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",9-Sep-19,2019,TV-PG,90 min,"Children & Family Movies, Comedies"
1,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,9-Sep-16,2016,TV-MA,94 min,Stand-Up Comedy
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,8-Sep-18,2013,TV-Y7-FV,1 Season,Kids' TV

In [57]:
# Let us also recall the list netflix_type and associated counts
print(netflix_type[0:10])
print(movie_count, tv_show_count, (movie_count/len(netflix_type)))

['Movie', 'Movie', 'TV Show', 'TV Show', 'Movie', 'TV Show', 'Movie', 'Movie', 'TV Show', 'Movie']
4265 1969 0.6841514276547963

In [58]:
# Create a boolean array called netflix_type_bool with True in the positions corresponding to 'Movie' 
# and False in the positions corresponding to 'TV Show' in the above list. 

# convert netflix_type to an array 
netflix_type_array = np.array(netflix_type)
netflix_type_array[0:5]

# construct the bool mask 
netflix_type_bool = ...

In [59]:
# summing a boolean mask 


# averaging a boolean mask

In [47]:
# extracting a smaller subset using the boolean mask

### **NumPy - Matrices and Tensors (Higher Order ndarrays)**

In [12]:
# Create a 3x2 (3 rows and 2 columns) matrix with first row containing first two even numbers 
# starting with the number 2, second row containing the next two even numbers, and so on. 
# Store you answer as even_matrix.

In [13]:
# Extract second element in the second row of the above matrix.

In [14]:
# Extract the sub-matrix formed by last two rows.

In [15]:
# Change all the entries in the sceond row of the matrix to 99.

In [16]:
# Print the sum of all the entries in the above matrix.

In [17]:
# Print the sum down the rows.

In [18]:
# Print the sum across the columns.

In [19]:
# Count the numbers of entires that are greater than 50.

### **NumPy - Image Manipulation**

In [20]:
# Create a 100x100 matrix with all entries zero.

In [21]:
# Change middle 20 rows and columns of the above matrix to 1.
# Store it as zero_matrix. 




# Output an image of the above matrix using plt.imshow() function.

In [22]:
# Change the above matrix to a boolean matrix. Store your answer as bool_matrix. 



# Output an image of the above matrix using plt.imshow() function.

In [23]:
# What does ~zero.matrix do?

#plt.imshow(~bool_matrix, cmap = "grey");
#plt.colorbar();

# **3. Pandas**

In [60]:
import pandas as pd

In [ ]:
# In what follows, X_df and Y_df are arbitrary/placeholder 
# Pandas DataFrames. z_series is an abrbitrary/placeholder Pandas Series.  
# Most of the functions and methods below work for both DataFrames and Series. 





# For importing Pandas Library as pd. 

import pandas as pd







# For reading data into the notebook as Pandas DataFrame from a .csv file. 

pd.read_csv("file_name.csv")                                # With default index. 
pd.read_csv("file_name.csv", index_col = "")                # With index set to your choice of column in the DataFrame. 






# For checking some basic features of the DataFrame. 

X_df.head()                                                 # First five rows.                       
X_df.tail()                                                 # Last five rows. 
X_df                                                        # First five and the last five rows. 
display(type(X_df), X_df.dytpes, X_df.shape)                # To check type, dtypes, and shape of the DataFrame.
X_df.info                                                   # Will return basic information about the DataFrame.







# Columns. 

X_df.columns                                                # Will return columns names. 

X_df.columns.to_numpy()                                     # Will return an ndarray containing column names. 
col_array = np.array(X_df.columns)                          # Will retuen an ndarray col_array containing column names. 

X_df.rename(columns = {"old_name": "new_name"})             # For changing column names. (Doesn't change the original DataFrame.)
X_df["col_name"] or X_df.col_name                           # For extracting a column as a Pandas Series.

X_df.set_index("col_name")                                  # Deletes old index and sets col_name as the new index.
X_df.reset_index()                                          # Will add the index as a separate column and the default index
                                                            # as the new index.
X_df["new_column"] = z_series                               # Adds z_series as a column to the DataFrame X_df.
X_df[["","",....,""]]                                       # Extracts multiple columns as a DataFrame. 







# Rows.

X_df.iloc[]                                  # For extracting via default indexing (0,1,2,....).
X_df.loc[]                                   # For extracting via the index. 
X_df[bool_mask]                              # For extracting via (correctly constructed) boolean mask. 








# Joining/Merging Dataframes.


X_df.join(Y_df, how = "")                                       # When there is a common index. 
                                                                # Will join Dataframes X_df and Y_df using how = "" method.
                                                                # (how could be "left", "right", "inner", and "outer".)


                                          
X_df.merge(Y_df, how = "")                                      # When there is No common index but a common column.

                                           
X_df.merge(Y_df, how = "", left_on = "", right_on = "")         # When there is No common index nor a common column.
                                                                # One needs to specify which columns to align by using
                                                                # left_on = "" and right_on = "".










# Computing basic statistics. 

X_df.sort_values("col_name")                                   # For sorting values with respect to the column col_name. 
X_df.describe().round()                                        # Returns various statistics for quantitative variables in
                                                               # the DataFrame.

X_df.groupby("col_name").agg("statistic_name")                 # Computes statistic_name for quantitative variables for 
                                                               # various groups in col_name. 

X_df.groupby("col_name").agg(                                  # For computing different statistics for different columns          
   new_col1 = ("col_name1", "statistic_name1"),                # with respect to the same grups in col_name. 
   new_col2 = ("col_name2", "statistic_name2"),
   new_col3 = ("col_name3", "statistic_name3")
)                                                              




pd.Dataframe # For creating a Pandas DataFrame from a dictionary, for example. 
my_df.sample(n = ) # Returns a random sample of items from an axis of object.

## **Pandas DataFrame - Eyeballing**

In [4]:
# Read the data as Pandas DataFrame. 
# Store it as salaries_df.

In [13]:
# First 5 rows of the DataFrame.

#salaries_df.head()

In [56]:
# Last 3 rows of the DataFrame.  

#salaries_df.tail(3)

In [57]:
# First 5 and last 5 rows of the DataFrame.

#salaries_df

In [16]:
# Let us explore some basic features of the DataFrame.  


#display(type(salaries_df), salaries_df.shape)

## **Pandas DataFrame - Basic Column Manipulations**

In [60]:
# Let us explore columns names.

#salaries_df.columns

In [61]:
# Store columns of the DataFrame as an ndarray called data_columns. (There are at least two ways.)





#type(data_columns)

In [62]:
# How to change names of columns?
# Rename "work_models" to "work_mode". 
# Store your answer as "salaries_df".




#salaries_df.head(3)

In [64]:
# Extracting a given column as a Pandas Series. 
# Extract "hours_per_week" as a Pandas Series called "col_1".




#type(col_1)

In [65]:
# Pandas Series is almost like an ndarray. Hence, all "np." functions work on a Pandas Series as well. 
# We will exploit this fact later in the lecture. 

#display(col_1.head(3), col_1.dtype, col_1.shape)

In [66]:
# Another way. 

#col_1_copy = salaries_df.hours_per_week
#col_1 == col_1_copy

In [70]:
# Can you convert a Pandas Series to a Pandas DataFrame?
# The following code will turn the original index to a new separate column, and will set Pandas default index
# 0,1,2,... to be the new index. Thereby, creating a Pandas DataFrame. 



#col_1_df = col_1.reset_index()

#display(type(col_1_df), col_1_df.head(3))

In [71]:
# How to add a Pandas Series as a column to a Pandas DataFrame?

# Create a Pandas Series containing information about salary earned per hour. 
# Store your series as "salary_every_hour". 







# Let us now add the Pandas Series "salary_every_hour" as a column (with the name 
# salary_per_hour) to the DataFrame "salaries_df". 






#salaries_df.head(3)

In [72]:
# How to set a column as an index (instead of default index coding 0,1,2,....)?
# Write a code to read the data as a Pandas DataFrame. Store it as "salaries_df_copy". 
# Also ensure the column work_year is the index. 




#salaries_df_copy = pd.read_csv("data_science_salaries_2.csv", index_col = "work_year")
#salaries_df_copy.head(3)




# For this data set it may be better to work with default index coding since we don't have a column 
# that has unique entries for different rows. However, it also depends on the context and the problem 
# we are trying to solve using the DataFrame.

In [73]:
# How to reset index to a different column?
# Delete the index "work_year" from the DataFrame "salaries_df_copy" and set the column "job_title" as the new index. 
# Display first three rows of your resulting DataFrame. 
# Write your code inside the display function so that DataFrame remains unaltered. 



#display()




# If you want to retain the old index as a column in your data set, then 
# the following code is a better choice. 

#display(salaries_df_copy.reset_index().set_index("job_title").head(3))

In [74]:
# How to extract mulptiple columns as a (smaller) DataFrame?
# Extract "salary_in_usd", "hours_per_week", and "job_title" as a separate (smaller) Pandas DataFrame.
# Store it as "salaries_subset_df". 




#display(type(salaries_subset_df), salaries_subset_df.head(3))

## **Pandas DataFrame - Extracting Rows**

In [75]:
# Let us look at DataFrames "salaries_df" and "salaries_df_copy". 

#display(salaries_df.head(2), salaries_df_copy.head(2))

In [76]:
# Extract rows 100 through 103 from the DataFrame "salaries_df". (index number)

In [77]:
# Extract all rows with "work_year" = 2024 from the DataFrame "salaries_df_copy". (index name)

In [78]:
# Extract all rows with "work_year" = 2024 from the DataFrame "salaries_df".
# Hint: Use a boolean mask "bool_mask".

In [79]:
# From the Pandas DataFrame "salaries_df", extract rows corresponding to 2024 from the column
# "salary_in_usd" and store it as "salary_2024_srs".

In [68]:
# From the Pandas DataFrame "salaries_df_copy", extract rows corresponsding to 2024 from the column 
# "salary_in_usd" and store it as "salary_2024_srs_copy". 

#salary_2024_srs_copy = salaries_df_copy["salary_in_usd"].filter(like = "2024")
#salary_2024_srs_copy

## **Pandas DataFrame - Let us do some statistics!**

In [21]:
# Let us recall salaries_df. 

#salaries_df.head()

In [22]:
# Sorting values.
# Sorted values of a quantiative variable is an important example of multi-variable statistic. 


# Sort Dataframe salaries_df so that salary_in_usd is arranged smallest to largest. 
#sorted_1 = salaries_df.sort_values("salary_in_usd")

# Sort Dataframe salaries_df so that salary_in_usd is arranged largest to smallest. 
#sorted_2 = salaries_df.sort_values("salary_in_usd", ascending = False)

#display(sorted_1.head(), sorted_2.head())

In [20]:
# A cool function for Pandas DataFrame to compute various statistics. 

#salaries_df.describe().round()

In [17]:
# What if we want to compute statistics for various groups? 

# Which groups? Let us work with "work_models".
# Compute means for the columns "salary_in_usd" and "hours_per_week" using the grouping 
# "work_models". Store your as "stats_1".

In [19]:
# What if we want to compute different statistics for different columns with respect 
# to the same groups?

#stats_2 = salaries_df.groupby("work_models").agg(
   #mean_salary_usd = ("salary_in_usd", "mean"),    
    #median_hours_week = ("hours_per_week", "median"),)

#stats_2

# **For loops and Functions in Python!**

### **For Loops in Python**

In [33]:
# Motivation 
a_list = ["first", "second", "third", "forth"]

Learning `for` loops in Python is a fundamental skill designed to move a programmer from performing manual, repetitive tasks to creating automated, efficient, and concise code. They are essential for iterating over data structures, reducing code redundancy, and handling automation, such as analyzing large datasets or file processing.

In [3]:
# Generic Syntax. (Don't run this cell.)

for {iteration variable} in {iterable}:
           # do things

- Each for loop starts with the keyword `for`.

- The `iteration variable` is a variable that is declared only in the scope of the loop that is used to 'point' at the elements in the sequence.

- The `iterable` is a data structure that contains the sequence of elements we are going to perform tasks on, for example a list or a dictionary.

In [25]:
# 1.A
# Loop over items in a list.
# Write a for loop to print every element of a_list. 

a_list = ["first", "second", "third", "forth"]

**Remark: When you call range, its value is not a list nor sequence of numbers. Loosely speaking, `range()` saves the instruction to iterate over a range of numbers. For example, `range(5)` defines the instruction to iterate over the first 5 numbers (starting at 0). That is why, used in a loop, it seems as if it is iterating over a list.**

In [26]:
# 1.B
# Compute sum squares of numbers from 1 to 10.
my_sum = 0

##  **Conditional Statements**

**Conditional statements allow you to excecute particular pieces of code when certain conditions are met; that is, they execute a piece of code when a Boolean value is True. Let's explore!**

In [47]:
# Let us quickly take a look at the following conditional statement. 

num_semesters = 3

if num_semesters <= 0:
    print('Not a valid input')
elif num_semesters <= 2:
    print('Freshman')
elif num_semesters <= 4:
    print('Sophomore')
elif num_semesters <= 6:
    print('Junior')
elif num_semesters <= 8:
    print('Senior')
else:
    print("NA")

Sophomore

## ***Exercise***

**Write a Python program to find those numbers which are divisible by $7$ and multiples of $5$, between $1500$ and $2700$ (both included). Recall `%` symbol in Python is called the Modulo Operator. It returns the remainder of dividing the left hand operand by right hand operand.**

In [27]:
# Create an empty list to store numbers that meet the given conditions.
new_list = []



# Iterate through numbers from 1500 to 2700 (inclusive).

    # Check if the number is divisible by 7 and 5 without any remainder.
   
        # If the conditions are met, convert the number to a string and append it to the list.
   

# Join the numbers in the list with a comma and print the result.

# ***Functions***

We have already used many functions in this class that are built into Python or are imported from different modules/packages.

Writing your own functions in Python is important because it leads to cleaner, more efficient, and easier-to-manage code. Functions help you follow core programming principles, such as modularity, abstraction, and the ***"Don't Repeat Yourself"*** (DRY) principle (Read This: <https://en.wikipedia.org/wiki/Don%27t_repeat_yourself>). 

For example, **Code Reusability:** Functions let you define a task once and call it whenever needed in your program, or even in different projects. This avoids repetitive coding and ensures consistency.

In [ ]:
def function_name(parameter1, parameter2=default_value, *args, **kwargs):
    """
    Docstring: This is an optional string that describes what the function does.
    It can span multiple lines.
    """
    # Function body: This is where the code that the function executes resides.
    # It must be indented.
    statement1
    statement2
    # ...
    return expression # Optional: returns a value from the function

Explanation of Elements:
- `def` keyword: This keyword is used to declare that a function is being defined.
  
- `function_name`: This is the identifier for the function, following Python's naming conventions (lowercase with underscores for multiple words).

- Parentheses `()`: These enclose the function's parameters (also known as arguments).

  - `parameter1`: A required positional argument.
  - `parameter2=default_value`: An optional argument with a default value. If the caller does not provide a value for this parameter, the default_value will be used.
  - `*args`: Allows the function to accept an arbitrary number of positional arguments, which are collected into a tuple.
  - `**kwargs`: Allows the function to accept an arbitrary number of keyword arguments, which are collected into a dictionary.
    

- Colon `:`: Marks the end of the function header and the beginning of the function body.

- Indentation: The lines of code that form the function's body must be consistently indented (typically with 4 spaces) after the colon. This indentation defines the scope of the function.

- Docstring (optional): A string literal immediately following the function header, enclosed in triple quotes (`"""Docstring"""` or `'''Docstring'''`). It provides documentation for the function and can be accessed via `function_name.__doc__`.

- `return` statement (optional): Used to send a value back to the caller of the function. If return is omitted or used without an expression, the function implicitly returns `None`.

<br>

Calling a Function:
- To execute the code within a function, you call it by its name followed by parentheses, passing any required arguments:

<br>
<br>
<br>
<br>
<br>

Let's now write some new functions ourselves!

#### Warm up!

In [41]:
# 0.1
# Write a function that doubles a value.



# Check your function.

#### 1. Write a function that takes in two real numbers `x` and `y`, and computes $ |x-y| $.

In [28]:
# Write your code here.
# Don't use abs function.

In [40]:
# Check your function.

#### 2. Given a real number `x`, write a function to compute its distance to zero on the real number line.

In [38]:
# Write your code here:

In [39]:
# Check your function.

#### 3. Given a real number `x`, write a function that would output: 
- its type (int or float),
- and its square root, provided `x` is non-negative and "NA" otherwise.

In [36]:
# Write your code here:

In [37]:
# Check your function.

#### 4. Consider a list `my_list = [2, 3, 5, 7, 11]`. Write a function that will take in an `np.` function (for example, `np.sum`) and output its application on `my_list`.

In [34]:
# Write your code here.

In [35]:
# Apply np.median to my_list.

#### 5. Create a function `flip_coins(n, prob)` that generates `n` random numbers (between 0 and 1) and returns the proportion of numbers that are less than `prob`.

In [32]:
# Wtite your code here.

In [33]:
# Check your function.
# Try large values of "n" and see if the output agrees with your intuition.

#### 6. Write a Python function that takes a string as input and returns a dictionary containing the number of uppercase and lowercase characters in the string. Any characters that cannot be categorized as uppercase or lowercase (e.g., symbols) should be counted as "other".
- Hint: Use may want to use `my_string.isupper()` and `my_string.islower()` methods that we learnt earlier in the semester.
- Hint: The plus-equals operator `+=` provides a convenient way to add a value to an existing variable and assign the new value back to the same variable.

In [31]:
# Write your code here.

In [30]:
# Check your function.

#### 7. Write a Python function that takes a list of strings as input and returns another list containing the unique elements from the input list, sorted in alphabetical order.
Hints: 
- First, create a set from the input list using `set(input_list)`. Since Python sets have no duplicates in them, this automatically removes duplicate entries from the list.
- Afterwards, sort the unique elements using the `sorted()`, which always returns a list.

In [28]:
# Write your code here.

In [29]:
# Check your function.

<br>
<br>
<br>

## **Some food for thought: Can we use the `print()` function instead of `return`?**

**Rule of Thumb**

- If the result needs to be used later, use `return`

- If it just needs to be seen, `print` is fine

You cannot use `print()` instead of `return` because they serve fundamentally different purposes in Python: `print()` is for displaying information to a human user, while `return` is for sending a value back to the program's code for further use.


**Code Reusability:** A function that returns a value acts like a self-contained operation that can be a building block for larger, more complex programs. For example, a function that calculates the sum of two numbers should `return` the sum so that the result can be used in subsequent calculations. If it only `print`ed the sum, the program would have no way to access that number internally.

**Error Prevention:** If a function uses `print()` but has no `return` statement, attempting to store its "result" in a variable will assign the value `None` to that variable, which can lead to unexpected errors in your program later on.

In [42]:
# Example 1

def double(x):
    return x * 2

print(double(5) + 3)  # Works

13

In [43]:
# Example 2

def double(x):
    print(x * 2)

print(double(5) + 3)  # Error!

10

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [44]:
# Example 3

type(double(5))

10

NoneType